---
type: yml
http_config:
  port: "8080"
auth:
  access_token_expire_time: "1h"
  refresh_token_expire_time: "168h"
db_config:
  username: "gameapp"
  port: 3308
  host: "localhost"
  db_name: "gameapp_db"
redis_config:
  host: "localhost"
  port: 6380
redis_presence:
  presence_key_expiration_time: "1h"






