---
type: yml
http_config:
  port: "8088"
auth:
  signing_key: "tokenpass"
  access_token_expire_time: "1h"
  refresh_token_expire_time: "168h"
db_config:
  port: 3308
  host: "localhost"
  db_name: "gameapp_db"






