version: '3.7'

services:
   gameapp-rabbitmq:
    image: rabbitmq:latest
    container_name: gameapp-rabbitmq
    restart: always
    ports:
     - 5672:5672
     - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: kalo
      RABBITMQ_DEFAULT_PASS: kalo
    volumes:
     - rabbitmq-lib:/var/lib/rabbitmq/
     - rabbitmq-log:/var/log/rabbitmq
   gameapp-redis:
     image: 'bitnami/redis:7.0'
     ports:
      - "6380:6379"
     command: redis-server --loglevel warning --protected-mode no --save "" --appendonly no
     container_name: gameapp-redis
     restart: always
     environment:
      - ALLOW_EMPTY_PASSWORD=yes
     volumes:
       - gameapp-redis-data:/bitnami/redis/data
   gameapp-database:
     image: mysql:8.0
     ports:
      - "3308:3306"
     container_name: gameapp-database
     volumes:
      - dbdata:/var/lib/mysql
     restart: always
     command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
     environment:
      MYSQL_ROOT_PASSWORD: gameappRoo7t0lk2o20
      MYSQL_DATABASE: gameapp_db
      MYSQL_USER: gameapp
      MYSQL_PASSWORD: gameappt0lk2o20


volumes:
  dbdata:
  gameapp-redis-data:
  rabbitmq-lib:
  rabbitmq-log:



